import type { Metadata } from "next";
import {Lato, Josefin_Sans} from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  style: ["normal", "italic"],
  variable: "--font-lato",
})

const josefin = Josefin_Sans({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "200", "600", "500"],
  style: ["normal", "italic"],
  variable: "--font-josefin",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${lato.className} ${josefin.className} antialiased bg-neutral-100`}
        >
          {children}

        </body>
      </AuthProvider>
    </html>
  );
}
